services:
  - type: web
    name: mogua-server
    runtime: java
    plan: free
    region: singapore
    buildCommand: |
      export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
      export PATH=$JAVA_HOME/bin:$PATH
      chmod +x gradlew
      ./gradlew build
    startCommand: java -jar build/libs/*.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://aws-0-ap-northeast-2.pooler.supabase.com:5432/postgres
      - key: SPRING_DATASOURCE_USERNAME
        value: postgres.binfslmwglspnwnkonzy
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
        value: org.postgresql.Driver
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_JPA_SHOW_SQL
        value: "true"
      - key: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
        value: org.hibernate.dialect.PostgreSQLDialect
      - key: SUPABASE_URL
        value: https://binfslmwglspnwnkonzy.supabase.co
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: SUPABASE_STORAGE_BUCKET_PROFILE
        value: profile-images
      - key: SUPABASE_STORAGE_BUCKET_MEETUP
        value: meetup-images
      - key: SUPABASE_STORAGE_BUCKET_REVIEW
        value: review-images
      - key: JWT_SECRET_KEY
        sync: false
      - key: JWT_ACCESS_TOKEN_EXPIRE_LENGTH
        value: "3600000"
      - key: JWT_REFRESH_TOKEN_EXPIRE_LENGTH
        value: "1209600000"
      - key: KAKAO_APIKEY
        sync: false
      - key: KAKAO_REDIRECT_URI
        value: https://your-render-domain.onrender.com/oauth/callback/kakao
