services:
  - type: web
    name: mogua-server
    runtime: java
    plan: free
    region: singapore
    buildCommand: ./gradlew build
    startCommand: java -jar build/libs/*.jar
    autoDeploy: true
    envVars:
      - key: JAVA_VERSION
        value: 17
      - key: JAVA_HOME
        value: /usr/lib/jvm/java-17-openjdk-amd64
