services:
  - type: web
    name: mogua-server
    env: java
    buildCommand: ./gradlew build
    startCommand: java -jar build/libs/*.jar
    envVars:
      - key: JAVA_VERSION
        value: 17
      - key: JAVA_HOME
        value: /usr/lib/jvm/java-17-openjdk-amd64
